version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - parceiroCerto-network

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - parceiroCerto-network



  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: parceiroCertoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

networks:
  parceiroCerto-network:
    driver: bridge