apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: danielugulino/authservice:latest
          ports:
            - containerPort: 8089
          env:
            - name: DBSOURCE
              value: parceiroCertoDB
            - name: DBUSER
              value: postgres
            - name: DBPASSWORD
              value: ugulino10
            - name: DBHOST
              value: postgis
            - name: DBPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8089
      targetPort: 8089