apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: danielugulino/bff:latest
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: bff
spec:
  type: ClusterIP
  selector:
    app: bff
  ports:
    - port: 8086
      targetPort: 8086