apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: danielugulino/bff:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
          - name: EUREKASERVER
            value: "http://server-registry:8761/eureka/"
          - name: ZPENDPOINT
            value: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: Service
metadata:
  name: bff
spec:
  type: ClusterIP
  selector:
    app: bff
  ports:
    - port: 8086
      targetPort: 8086