apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-registry
  template:
    metadata:
      labels:
        app: server-registry
    spec:
      containers:
        - name: server-registry
          image: danielugulino/serverregistry:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKAHOST
              value: server-registry
---
apiVersion: v1
kind: Service
metadata:
  name: server-registry
spec:
  type: ClusterIP
  selector:
    app: server-registry
  ports:
    - port: 8761
      targetPort: 8761