apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: danielugulino/userservice:latest
          env:
            - name: DBSOURCE
              value: parceiroCertoDB
            - name: DBUSER
              value: postgres
            - name: DBPASSWORD
              value: ugulino10
            - name: DBHOST
              value: postgis
            - name: DBPORT
              value: "5432"
            - name: DTSOURCE
              value: "/app/data/"
            - name: EUREKASERVER
              value: "http://server-registry:8761/eureka/"
            - name: ZPENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082