name: Backend Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY_P }}
      - name: Run Kubernets
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_HOST << 'EOF'
            ls
            cd /home/parceiroCerto
            git pull
            minikube start
            sleep 15
            cd ./Infra
            ./run.sh
          EOF

          
      
        
