name: Backend Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: parceiroCertoDB
        ports:
          - 5432:5432

      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672
      eureka_server:
        image: danielugulino/serverregistry:latest
        env:
          EUREKA_SERVER_PORT: 8761
        ports:
          - 8761:8761

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login in Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permissions to maven
        run: |
          chmod +x ./ApiGateway/mvnw
          chmod +x ./AuthService/mvnw
          chmod +x ./BFF/mvnw
          chmod +x ./ChatService/mvnw
          chmod +x ./FeedbackService/mvnw
          chmod +x ./ServerRegistry/mvnw
          chmod +x ./TaskService/mvnw
          chmod +x ./UserService/mvnw

      - name: Make executable .sh files
        run: |
          chmod +x ./ApiGateway/build.sh
          chmod +x ./AuthService/build.sh
          chmod +x ./BFF/build.sh
          chmod +x ./ChatService/build.sh
          chmod +x ./FeedbackService/build.sh
          chmod +x ./ServerRegistry/build.sh
          chmod +x ./TaskService/build.sh
          chmod +x ./UserService/build.sh

      - name: Run executable .sh files
        run: |
          ./ApiGateway/build.sh
          ./AuthService/build.sh
          ./BFF/build.sh
          ./ChatService/build.sh
          ./FeedbackService/build.sh
          ./ServerRegistry/build.sh
          ./TaskService/build.sh
          ./UserService/build.sh
